include "../src/include/ez80.inc"
include "../src/include/ti84pceg.inc"
include "../bos.inc"
syscalllib "gfx"
export_ptr bos.gfx_BlitBuffer, "BlitBuffer"
export_ptr bos.gfx_PrintString, "PrintString"
export_ptr bos.gfx_BufClear, "BufClear"
export_ptr bos.gfx_LcdClear, "LcdClear"
export_ptr bos.gfx_SetDraw, "SetDraw"
export_ptr bos.gfx_SwapTextColors, "SwapTextColors"
export_ptr bos.gfx_SetFont, "SetFont"
export_ptr bos.gfx_SetDefaultFont, "SetDefaultFont"
export_ptr bos.gfx_Compute, "Compute"
export_ptr bos.gfx_FillRectangle, "FillRectangle"
export_ptr bos.gfx_FillScreen, "FillScreen"
export_ptr bos.gfx_GetFontPtr, "GetFontPtr"
export_ptr bos.gfx_HorizLine, "HorizLine"
export_ptr bos.gfx_InitStdPalette, "InitStdPalette"
export_ptr bos.gfx_NextLine, "NextLine"
export_ptr bos.gfx_PrintChar, "PrintChar"
export_ptr bos.gfx_PrintHexA, "PrintHexA"
export_ptr bos.gfx_PrintUInt, "PrintUInt"
export_ptr bos.gfx_Rectangle, "Rectangle"
export_ptr bos.gfx_Set8bpp, "Set8bpp"
export_ptr bos.gfx_Set16bpp, "Set16bpp"
export_ptr bos.gfx_SetTextXY, "SetTextXY"
export_ptr bos.gfx_Sprite, "Sprite"
export_ptr bos.gfx_Sprite2x, "Sprite2x"
export_ptr bos.gfx_VertLine, "VertLine"
export_ptr bos.gfx_PrintStringXY, "PrintStringXY"
export_ptr bos.gfx_GetTextX, "GetTextX"
export_ptr bos.gfx_GetTextY, "GetTextY"
export_ptr bos.gfx_BlitScreen, "BlitScreen"
export_ptr bos.gfx_ZeroVRAM, "ZeroVRAM"
end syscalllib