include "../src/include/ez80.inc"
include "../src/include/ti84pceg.inc"
include "../bos.inc"
syscalllib "gui"
export_ptr bos.gui_DrawConsoleWindow, "DrawConsoleWindow"
export_ptr bos.gui_Input, "Input"
export_ptr bos.gui_NewLine, "NewLine"
export_ptr bos.gui_Print, "Print"
export_ptr bos.gui_PrintInt, "PrintInt"
export_ptr bos.gui_Scroll, "Scroll"
export_ptr bos.gui_InputNoClear, "InputNoClear"
export_ptr bos.gui_PrintChar, "PrintChar"
export_ptr bos.gui_PrintString, "PrintString"
export_ptr bos.gui_PrintLine, "PrintLine"
export_ptr bos.gui_PrintUInt, "PrintUInt"
end syscalllib