include "../src/include/ez80.inc"
include "../src/include/ti84pceg.inc"
include "../bos.inc"
syscalllib "sys"
export_ptr bos.sys_ExecuteFile, "ExecuteFile"
export_ptr bos.sys_AddHLAndA, "AddHLAndA"
export_ptr bos.sys_AnyKey, "AnyKey"
export_ptr bos.sys_FreeAll, "FreeAll"
export_ptr bos.sys_GetKey, "GetKey"
export_ptr bos.sys_KbScan, "KbScan"
export_ptr bos.sys_Malloc, "Malloc"
export_ptr bos.sys_MemSet, "MemSet"
export_ptr bos.sys_WaitKey, "WaitKey"
export_ptr bos.sys_WaitKeyCycle, "WaitKeyCycle"
export_ptr bos.sys_EraseFlashSector, "EraseFlashSector"
export_ptr bos.sys_FlashUnlock, "FlashUnlock"
export_ptr bos.sys_FlashLock, "FlashLock"
export_ptr bos.sys_HLToString, "HLToString"
export_ptr bos.sys_WriteFlash, "WriteFlash"
export_ptr bos.sys_WriteFlashA, "WriteFlashA"
export_ptr bos.sys_JoinArgv, "JoinArgv"
export_ptr bos.sys_Free, "Free"
export_ptr bos.sys_CallExecuteFile, "CallExecuteFile"
export_ptr bos.sys_JumpExecuteFile, "JumpExecuteFile"
export_ptr bos.sys_OpenDevice, "OpenDevice"
export_ptr bos.sys_SetOnInterruptHandler, "SetOnInterruptHandler"
export_ptr bos.sys_ExecuteFileHL, "ExecuteFileHL"
export_ptr bos.sys_TurnOff, "TurnOff"
export_ptr bos.sys_NextProcessId, "NextProcessId"
export_ptr bos.sys_PrevProcessId, "PrevProcessId"
export_ptr bos.sys_FreeProcessId, "FreeProcessId"
export_ptr bos.sys_FreeRunningProcessId, "FreeRunningProcessId"
export_ptr bos.sys_CheckMallocRAM, "CheckMallocRAM"
export_ptr bos.sys_Malloc32Align32, "Malloc32Align32"
export_ptr bos.sys_Malloc64Align256, "Malloc64Align256"
export_ptr bos.sys_OpenFileInPath, "OpenFileInPath"
export_ptr bos.sys_VarString, "VarString"
export_ptr bos.sys_MallocPersistent, "MallocPersistent"
export_ptr bos.sys_OpenFileInVar, "OpenFileInVar"
export_ptr bos.sys_ReadSectorCache, "ReadSectorCache"
export_ptr bos.sys_WriteSectorCache, "WriteSectorCache"
export_ptr bos.sys_OpenFileInLib, "OpenFileInLib"
export_ptr bos.sys_LoadHookThreads, "LoadHookThreads"
export_ptr bos.sys_WaitKeyUnpress, "WaitKeyUnpress"
export_ptr bos.sys_MallocDupStr, "MallocDupStr"
export_ptr bos.sys_MallocDupStrN, "MallocDupStrN"
export_ptr bos.sys_GetExecType, "GetExecType"
export_ptr bos.sys_GetExecTypeFD, "GetExecTypeFD"
end syscalllib