
; BOS graphics routines
; Mostly taken from Cesium and refactored to run from flash

include 'gfx/BlitBuffer.asm'
include 'gfx/BufClear.asm'
include 'gfx/Compute.asm'
include 'gfx/FillRectangle.asm'
include 'gfx/HorizLine.asm'
include 'gfx/InitStdPalette.asm'
include 'gfx/LcdClear.asm'
include 'gfx/NextLine.asm'
include 'gfx/PrintChar.asm'
include 'gfx/PrintHexA.asm'
include 'gfx/PrintString.asm'
include 'gfx/PrintUInt.asm'
include 'gfx/Rectangle.asm'
include 'gfx/Set8bpp.asm'
include 'gfx/Set16bpp.asm'
include 'gfx/SetDefaultFont.asm'
include 'gfx/SetDraw.asm'
include 'gfx/Sprite.asm'
include 'gfx/SetTextXY.asm'
include 'gfx/VertLine.asm'

