
; BOS system routines

include 'sys/AddHLAndA.asm'
include 'sys/AnyKey.asm'
include 'sys/EraseFlashSector.asm'
include 'sys/ExecuteFile.asm'
include 'sys/ExecuteFileEntryPoint.asm'
include 'sys/ExecuteInRAM.asm'
include 'sys/Free.asm'
include 'sys/FlashLock.asm'
include 'sys/FlashUnlock.asm'
include 'sys/GetKey.asm'
;include 'sys/InputString.asm'
include 'sys/KbScan.asm'
include 'sys/Malloc.asm'
include 'sys/memcmp.asm'
include 'sys/MemSet.asm'
include 'sys/WaitKey.asm'
include 'sys/WaitKeyCycle.asm'
include 'sys/WriteFlash.asm'

