
	jp boot_os                  ; rst $00
	jp handle_interrupt
	jp HandleInstruction        ; rst $10 thread control instructions and more
	jp sc_HandleSysCall         ; rst $18
	jp DONOTHING                ; rst $20
	jp handle_offsetinstruction ; rst $28
	jp DONOTHING ;handle_rst30
	include 'tiosjt.asm'
	dd (($022400-$) shr 2) dup $CD or handle_unimplemented shl 8
;$=$022400
	jp sys_ExecuteFile
	jp os_GetOSInfo
	jp fs_OpenFile
	jp fs_GetSectorAddress
	jp fs_CheckDirExists
	jp fs_CeilDivBySector
	jp fs_CopyFileName
	jp fs_Read
	jp fs_Write
	jp sys_AddHLAndA
	jp sys_AnyKey
	jp sys_FreeAll
	jp sys_GetKey
	jp sys_KbScan
	jp sys_Malloc
	jp fs_CreateRamFile
	jp sys_MemSet
	jp fs_AllocRam
	jp sys_WaitKey
	jp sys_WaitKeyCycle
	jp gui_DrawConsoleWindow
	jp gui_Input
	jp gui_NewLine
	jp gui_Print
	jp gui_PrintInt
	jp gui_Scroll
	jp gfx_BlitBuffer
	jp gfx_PrintString
	jp _MemClear
	jp _PushOP1
	jp _PopOP1
	jp _Mov9ToOP1
	jp _CpHLDE
	jp _Mov8b
	jp _ChkFindSym
	jp _LoadDEInd_s
	jp _EnoughMem
	jp _InsertMem
	jp _SetHLUTo0
	jp _PutS
	jp _GetCSC
	jp _NewLine
	jp _ClrScrn
	jp _HomeUp
	jp _ErrMemory
	jp _DrawStatusBar
	jp _os_GetSystemInfo
	jp _UsbPowerVbus
	jp _UsbUnpowerVbus
	jp sys_EraseFlashSector
	jp sys_FlashUnlock
	jp sys_FlashLock
	jp fs_CreateFile
	jp strupper
	jp strlower
	jp fs_AbsPath
	jp fs_MultByBytesPerSector
	jp _LoadLibraryOP1
	jp fs_OpenFileInDir
	jp fs_SetSize
	jp fs_WriteFile
	jp sys_HLToString
	jp fs_DeleteFile
	jp _DelVar
	jp _CreateVar
	jp gui_InputNoClear
	jp fs_InitClusterMap
	jp sys_WriteFlash
	jp sys_WriteFlashA
	jp sys_JoinArgv
	jp fs_PathLen
	jp fs_ParentDir
	jp fs_StrToFileEntry
	jp fs_DirList
	jp sys_Free
	jp sys_CallExecuteFile
	jp sys_JumpExecuteFile
	jp drv_InitDevice
	jp fs_CopyFile
	jp sys_GetRandomAddress
	jp sys_Random8
	jp sys_Random32
	jp fs_GetSector
	jp fs_WriteByte
	jp fs_RenameFile
	jp _SetCursorPos
	jp fs_CreateDir
	jp gfx_BufClear
	jp gfx_LcdClear
	jp fs_SanityCheck
	jp sys_SetOnInterruptHandler
	jp gui_PrintChar
	jp gfx_SetDraw
	jp gui_PrintString
	jp gui_PrintLine
	jp gui_PrintUInt
	jp DONOTHING ;sys_WriteFlashFullRam
	jp DONOTHING ;sys_WriteFlashByteFullRam
	jp fs_GetFilePtrRaw
	jp DONOTHING ;sys_ExecuteFileFromPtr
	jp sys_ExecuteFileHL
	jp sys_TurnOff
	jp sys_NextProcessId
	jp sys_PrevProcessId
	jp sys_FreeProcessId
	jp fs_GarbageCollect
	jp gfx_SwapTextColors
	jp fs_WriteNewFile
	jp gfx_SetFont
	jp gfx_SetDefaultFont
	jp sys_FreeRunningProcessId
	jp util_Zx7Decompress
	jp sys_CheckMallocRAM
	jp gfx_Compute
	jp gfx_FillRectangle
	jp gfx_FillScreen
	jp gfx_GetFontPtr
	jp gfx_HorizLine
	jp gfx_InitStdPalette
	jp gfx_NextLine
	jp gfx_PrintChar
	jp gfx_PrintHexA
	jp gfx_PrintUInt
	jp gfx_Rectangle
	jp gfx_Set8bpp
	jp gfx_Set16bpp
	jp gfx_SetTextXY
	jp gfx_Sprite
	jp gfx_Sprite2x
	jp gfx_VertLine
	jp sys_Malloc32Align32
	jp sys_Malloc64Align256
	jp gfx_PrintStringXY
	jp gfx_GetTextX
	jp gfx_GetTextY
	jp DONOTHING ; fs_CheckWritable
	jp DONOTHING ; fs_CheckWritableFD
	jp sys_OpenFileInPath
	jp sys_VarString
	jp fs_GetFreeSpace
	jp fs_GetFDPtrRaw
	jp fs_GetFDLenRaw
	jp _OP1ToPath
	jp th_WaitKeyCycle
	jp fs_JoinPath
	jp sys_MallocPersistent
	jp sys_OpenFileInVar
	jp fs_BaseName
	jp fs_MoveFile
	jp fs_WriteDirectly
	jp _UnpackUpdates
	jp sys_ReadSectorCache
	jp sys_WriteSectorCache
	jp sys_OpenFileInLib
	jp sys_LoadHookThreads
	jp gfx_BlitScreen
	jp th_CreateThread
	jp gfx_ZeroVRAM
	jp th_KillThread
	jp fs_GetFilePtr
	jp fs_GetFDPtr
	jp fs_GetFDLen
	jp fs_ArcUnarcFD
	jp util_Zx0Decompress
	jp sys_WaitKeyUnpress
	jp sys_MallocDupStr
	jp sys_MallocDupStrN
	jp _SearchSymTable
	jp fs_Rename
	jp fs_AllocChk
	jp sys_GetExecType
	jp sys_GetExecTypeFD
	jp util_Zx7Compress
	jp sys_OpenRecoveryMenu
	jp util_Relocate
	jp fs_GetFDAttr
	jp util_InitAllocSymList
	jp util_AppendSymList
	jp util_RemoveFromSymList
	jp util_SearchSymList
	jp util_FreeSymList
	jp sys_Exec
	jp sys_ExecV
	jp sys_ExecData
	jp sys_ExecBegin
	jp sys_ExecContinue
	jp fs_IsOSBackupPresent ; this has to be in the jump table so the installer can find it
	jp util_SHA256
	jp str_FromByte
	jp str_FromInt
	jp str_FromLong
	jp str_ToInt
	jp gui_CharFromCode
	jp sys_ExecuteFileArgcArgv
	jp drv_OpenDevice
	jp drv_OpenDeviceFD
	jp drv_GetDMA
	jp drv_GetChar
	jp drv_PutChar
	jp drv_Read
	jp drv_Write
	jp gui_PrintStdout
	jp sys_CallExecuteFileHere
	jp fsd_Open
	jp fsd_Close
	jp fsd_CloseAll
	jp fsd_Read
	jp fsd_Write
	jp fsd_Resize
	jp fsd_WriteStr
	jp fsd_InRam
	jp fsd_IsOpen
	jp fsd_Archive
	jp fsd_UnArchive
	jp fsd_Seek
	jp fsd_Tell
	jp fsd_ForceClose
	jp fsd_GetSize
	jp fsd_GetDataPtr
	jp sys_AllocHeap
    jp fs_ExtractRootDir
    jp fs_ExtractOSBinaries
    jp fs_ExtractOSOptBinaries
	
; end of jump table
