
	jp boot_os
	jp handle_interrupt
	jp HandleInstruction ;thread control instructions and more
	jp DONOTHING
	jp DONOTHING
	jp handle_offsetcall ;handle_rst28
	jp DONOTHING ;handle_rst30
	jp sys_ExecuteFile
	jp os_GetOSInfo
	jp fs_OpenFile
	jp fs_GetSectorAddress
	jp fs_CheckDirExists
	jp fs_GetPathLastName
	jp fs_CopyFileName
	jp fs_Read
	jp fs_Write
	jp sys_AddHLAndA
	jp sys_AnyKey
	jp sys_FreeAll
	jp sys_GetKey
	jp sys_KbScan
	jp sys_Malloc
	jp DONOTHING
	jp sys_MemSet
	jp DONOTHING
	jp sys_WaitKey
	jp sys_WaitKeyCycle
	jp gui_DrawConsoleWindow
	jp gui_Input
	jp gui_NewLine
	jp gui_Print
	jp gui_PrintInt
	jp gui_Scroll
	jp gfx_BlitBuffer
	jp gfx_PrintString
	jp _MemClear
	jp _PushOP1
	jp _PopOP1
	jp _Mov9ToOP1
	jp _CpHLDE
	jp _Mov8b
	jp _ChkFindSym
	jp _LoadDEInd_s
	jp _EnoughMem
	jp _InsertMem
	jp _SetHLUTo0
	jp _PutS
	jp _GetCSC
	jp _NewLine
	jp _ClrScrn
	jp _HomeUp
	jp _ErrMemory
	jp _DrawStatusBar
	jp _os_GetSystemInfo
	jp _UsbPowerVbus
	jp _UsbUnpowerVbus
	jp sys_EraseFlashSector
	jp sys_FlashUnlock
	jp sys_FlashLock
	jp fs_CreateFile
	jp strupper
	jp strlower
	jp fs_AbsPath
	jp fs_MultByBytesPerSector
	jp _LoadLibraryOP1
	jp fs_OpenFileInDir
	jp fs_SetSize
	jp fs_WriteFile
	jp sys_HLToString
	jp fs_DeleteFile
	jp _DelVar
	jp _CreateVar
	jp gui_InputNoClear
	jp fs_InitClusterMap
	jp sys_WriteFlash
	jp sys_WriteFlashA
	jp DONOTHING
	jp DONOTHING
	jp fs_ParentDir
	jp fs_StrToFileEntry
	jp fs_DirList
	jp sys_Free
	jp sys_CallExecuteFile
	jp sys_JumpExecuteFile
	jp sys_InitDevice
	jp sys_DeinitDevice
	jp sys_GetDeviceAddress
	jp sys_ReadDevice
	jp sys_WriteDevice
	jp fs_GetSector
	jp fs_WriteByte
	jp fs_RenameFile
	jp _SetCursorPos
	jp fs_CreateDir
	jp gfx_BufClear
	jp gfx_LcdClear
	jp fs_SanityCheck
	jp sys_SetupOnInterruptHandler
	jp gui_PrintChar
	jp gfx_SetDraw
	jp gui_PrintString
	jp gui_PrintLine
	jp gui_PrintUInt
	jp sys_WriteFlashFullRam
	jp sys_WriteFlashByteFullRam
	jp fs_GetFilePtr
	jp sys_ExecuteFileFromPtr
	jp sys_ExecuteFileHL
	jp sys_TurnOff
	jp sys_NextProcessId
	jp sys_PrevProcessId
	jp sys_FreeProcessId
	jp fs_GarbageCollect
	jp gfx_SwapTextColors
	jp fs_WriteNewFile
	jp gfx_SetFont
	jp gfx_SetDefaultFont
	jp sys_FreeRunningProcessId
	jp util_Zx7Decompress
	jp sys_CheckMallocRAM
	jp gfx_Compute
	jp gfx_FillRectangle
	jp gfx_FillScreen
	jp gfx_GetFontPtr
	jp gfx_HorizLine
	jp gfx_InitStdPalette
	jp gfx_NextLine
	jp gfx_PrintChar
	jp gfx_PrintHexA
	jp gfx_PrintUInt
	jp gfx_Rectangle
	jp gfx_Set8bpp
	jp gfx_Set16bpp
	jp gfx_SetTextXY
	jp gfx_Sprite
	jp gfx_Sprite2x
	jp gfx_VertLine
	jp sys_Malloc32Align32
	jp sys_Malloc64Align256
	jp gfx_PrintStringXY
	jp gfx_GetTextX
	jp gfx_GetTextY
	jp fs_CheckWritable
	jp fs_CheckWritableFD
	jp sys_OpenFileInPath
	jp sys_VarString
	jp fs_GetFreeSpace
	jp fs_GetFDPtr
	jp fs_GetFDLen
	jp _OP1ToPath
	jp th_WaitKeyCycle
	jp fs_JoinPath
	jp sys_MallocPersistent
	jp sys_OpenFileInVar
	jp fs_BaseName
	jp fs_MoveFile
