name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - run: wget https://github.com/CE-Programming/toolchain/releases/download/v9.2.2/linux_CEdev_v9.2.2.tar.gz
    - run: tar -xzf linux_CEdev_v9.2.2.tar.gz
    - run: export CEDEV="~/CEdev"
    - run: export PATH="$PATH:$CEDEV/bin"
    - run: git clone https://github.com/beckadamtheinventor/BOS.git --recursive
    - run: make -C BOS
      
